//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISBEntities : DbContext
    {
        public ISBEntities()
            : base("name=ISBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<loaivanban> loaivanbans { get; set; }
        public virtual DbSet<vanban> vanbans { get; set; }
    }
}
