//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vanban
    {
        public System.Guid Id { get; set; }
        public string Sovb { get; set; }
        public string Trichyeu { get; set; }
        public string Noidung { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
        public string Nguoidang { get; set; }
        public Nullable<int> Idloaivb { get; set; }
        public string Url { get; set; }
        public string Donvigui { get; set; }
        public string TenFile { get; set; }
    
        public virtual loaivanban loaivanban { get; set; }
    }
}
